#!/bin/bash
############################
# .make.sh
# This script updates the current version's of dot files and SSH config
############################

# TODO: Update the project's working directory so they match in both computers

########## Variables
dir=$(pwd)
files=".bashrc .bash_profile"    # list of files we will be installing to the user's home directory

# Iterate over the dot files and replace the current versions with this project's version
for file in $files; do
    echo "Updating local file: $file"
    rm ~/$file
    cp $dir/$file ~/$file
    . ~/$file
done

# Next we will copy this project's version of the ssh config to the ~/.ssh directory
echo "Updating ssh config file"
sshdir=~/.ssh/
rm $sshdir/config
cp $dir/config $sshdir/config
