#!/bin/bash
############################
# .make.sh
# This script creates symlinks from the home directory to any desired dotfiles in the dotfiles project
############################

########## Variables

dir=$(pwd)
files=".bashrc .bash_profile"    # list of files/folders to symlink in homedir

# Create a symlink to this setup file
ln -s ${dir}/dotfiles_setup ~/bin/dotfiles_setup

# Create a symlink to the webservers script
ln -s ${dir}/webservers ~/bin/webservers

# Create a symlink to the ssh config script
ln -s ${dir}/config ~/.ssh/config

for file in $files; do
    echo "Creating symlink: ~/$file -> $dir/$file"
    source ${dir}/${file}
    ln -s ${dir}/${file} ~/${file}
done
