#!/usr/bin/env bash

CYAN="\033[36m"
BLUE="\033[34m"
GREEN="\033[32m"
RED="\033[31m"
YELLOW="\033[33m"
ENDCOLOR="\033[m"

BOLD=$(tput bold)
NORMAL=$(tput sgr0)

#############################################################################################
# Screen shots
#############################################################################################

echo -e "[$GREEN ${BOLD}INFO${NORMAL} $ENDCOLOR] Setting screen shot default location"
defaults write com.apple.screencapture location -string "${HOME}/Documents/Screenshots"


##########################################################################
# Activity Monitor
##########################################################################

echo -e "[$GREEN ${BOLD}INFO${NORMAL} $ENDCOLOR] Setting activity monitor defaults"
# Show the main window when launching Activity Monitor
defaults write com.apple.ActivityMonitor OpenMainWindow -bool true

# Visualize CPU usage in the Activity Monitor Dock icon
defaults write com.apple.ActivityMonitor IconType -int 5

# Show all processes in Activity Monitor
defaults write com.apple.ActivityMonitor ShowCategory -int 0

# Sort Activity Monitor results by CPU usage
defaults write com.apple.ActivityMonitor SortColumn -string "CPUUsage"
defaults write com.apple.ActivityMonitor SortDirection -int 0


#####################################################################
# Finder
#####################################################################

echo -e "[$GREEN ${BOLD}INFO${NORMAL} $ENDCOLOR] Setting finder defaults"
# Show hidden files and file extensions by default
defaults write com.apple.finder AppleShowAllFiles -bool true
defaults write NSGlobalDomain AppleShowAllExtensions -bool true