#!/bin/bash
############################
# .make.sh
# This script updates the current version's of dot files and SSH config
############################

# TODO: Update the project's working directory so they match in both computers

# Global Variables
dir=$(pwd)

echo "====================================================="
echo "[BEGIN] dotfiles setup.."
echo "====================================================="

# Install all bash dotfiles
echo "[INFO] Installing bash dotfiles.."
bashfiles=".bashrc .bash_profile"

for file in $bashfiles; do
    echo "[BASH] Updating local file: $file"
    rm ~/$file
    cp $dir/bash/$file ~/$file
    . ~/$file
done

echo " "
echo "[INFO] Installing ssh related files.."
# Next we will copy this project's version of the ssh config to the ~/.ssh directory
echo "[SSH] Updating config file"
sshdir=~/.ssh/
rm $sshdir/config
cp $dir/ssh/config $sshdir/config
