#!/bin/bash
####################################################################################
# This script updates the current version's of my bash dotfiles and SSH config
####################################################################################

# Global Variables
CYAN="\033[36m"
BLUE="\033[34m"
GREEN="\033[32m"
RED="\033[31m"
ENDCOLOR="\033[m"

BOLD=$(tput bold)
NORMAL=$(tput sgr0)

# Check the dotfiles project installation is correct
if [ ! -d "$HOME/Dropbox/dotfiles" ]; then
    echo -e "[$RED ${BOLD}ERROR$ENDCOLOR ${NORMAL}] The dotfiles project is not installed in the expected directory: $BLUE $HOME/Dropbox/dotfiles $ENDCOLOR"
    echo -e "[$RED ${BOLD}ERROR$ENDCOLOR ${NORMAL}] Exiting.."
    exit 1
fi

# The script expects the dotfiles project to be installed in the following directory,
# the check above this verifies that it exists before continuing
dir=$HOME/Dropbox/dotfiles

echo "====================================================="
echo -e "[$GREEN ${BOLD}BEGIN$ENDCOLOR ${NORMAL}] Updating this computer's dotfiles"
echo "====================================================="

# Install all bash shell dotfiles
bashfiles=".bashrc .bash_profile"
for file in $bashfiles; do
    echo -e "[$GREEN ${BOLD}INFO$ENDCOLOR ${NORMAL}] Updating and sourcing bash dotfile: [$BLUE $file $ENDCOLOR]"
    rm -rf $HOME/$file
    cp $dir/shell/$file $HOME/$file
    . $HOME/$file
done

# Next we will copy this project's version of the ssh config to the ~/.ssh directory
echo -e "[$GREEN ${BOLD}INFO$ENDCOLOR ${NORMAL}] Updating SSH config:                [$BLUE config $ENDCOLOR]"
sshdir=~/.ssh
rm -rf $sshdir/config
cp $dir/ssh/config $sshdir/config
