#!/bin/bash
############################
# .make.sh
# This script updates the current version's of dot files and SSH config
############################


# Global Variables
CYAN="\033[36m"
BLUE="\033[34m"
GREEN="\033[32m"
RED="\033[31m"
ENDCOLOR="\033[m"
dir=$HOME/Dropbox/dotfiles # Project directory: The project will be checked out in dropbox

echo "====================================================="
echo -e "[$GREEN BEGIN $ENDCOLOR] Updating computer's dotfiles"
echo "====================================================="

# Install all bash shell dotfiles
bashfiles=".bashrc .bash_profile"

for file in $bashfiles; do
    echo -e "[ INFO ] Updating bash dotfile: [$BLUE $file $ENDCOLOR]"
    rm -rf $HOME/$file
    cp $dir/shell/$file $HOME/$file
    . $HOME/$file
done

# Next we will copy this project's version of the ssh config to the ~/.ssh directory
echo -e "[ INFO ] Updating SSH config:   [$BLUE config $ENDCOLOR]"
sshdir=~/.ssh
rm -rf $sshdir/config
cp $dir/ssh/config $sshdir/config

echo -e "[$GREEN END $ENDCOLOR] Update Complete"